session_name: "myitjournal"
global_options:
  automatic-rename: 'off'
start_directory: ${PWD}
windows:
- window_name: myitjournal
  layout: main-horizontal
  panes:
  - shell_command:
    - tmux resize-pane -t :.1 -y 8
    - conda activate itjournal
    - mkdocs serve
  - focus: true
    start_directory: ${PWD}/docs/
    shell_command:
    - sleep 2 && open http://localhost:8000 && clear
  - start_directory: ${PWD}/docs/
