---
name: myitjournal
dependencies:
  - python=3
  - pip
  - pip:
      - zensical
      - mkdocs-git-revision-date-localized-plugin
      - mkdocs-glightbox
      - argcomplete
      - pre-commit
      - yamllint
