---
name: myitjournal
dependencies:
  - python=3
  - pip
  - pip:
      - mkdocs-material
      - mkdocs-git-revision-date-localized-plugin
      - mkdocs-git-authors-plugin
      - ansible
      - ansible-lint
      - argcomplete
      - molecule
      - molecule-podman
      - pre-commit
      - yamllint
