name: myitjournal
dependencies:
  - python=3
  - pip
  - pip:
      - mkdocs-material
      - mkdocs-git-revision-date-plugin
      - ansible
      - ansible-lint
      - argcomplete
      - yamllint
